node_id: 0 #ID of the host node
n_containers: 4
duration: 600 # in seconds
sleep_lambda: 0.1 # Lambda value for exponential distr, E[sleep_time] = 1/lambda
istream_player_config_path: ./resources/4s_segments_times.yaml
sequences:
  - "loot"
  - "soldier"
  - "longdress"
  - "redandblack"